<?php
	$major = array();
    array_push($major, "Undecided");
    array_push($major, "Computer Science");
    array_push($major, "Computational Media");
    array_push($major, "Architecture");
    array_push($major, "Building Construction");
    array_push($major, "Industrial Design");
    array_push($major, "Aerospace Engineering");
    array_push($major, "Biomedical Engineering");
    array_push($major, "Chemical and Biomolecular Engineering");
    array_push($major, "Civil Engineering");
    array_push($major, "Computer Engineering");
    array_push($major, "Electrical Engineering");
    array_push($major, "Environmental Engineering");
    array_push($major, "Industrial Engineering");
    array_push($major, "Materials Science and Engineering");
    array_push($major, "Mechanical Engineering");
    array_push($major, "Nuclear and Radiological Engineering");
    array_push($major, "Business Administration");
    array_push($major, "Applied Language and Intercultural Studies");
    array_push($major, "Economics");
    array_push($major, "Economics and International Affairs");
    array_push($major, "Global Economics and Modern Languages");
    array_push($major, "History, Technology, and Society");
    array_push($major, "International Affairs");
    array_push($major, "International Affairs and Modern Language");
    array_push($major, "Literature, Media, and Communication");
    array_push($major, "Public Policy");
    array_push($major, "Applied Mathematics");
    array_push($major, "Applied Physics");
    array_push($major, "Biochemistry");
    array_push($major, "Biology");
    array_push($major, "Chemistry");
    array_push($major, "Discrete Mathematics");
    array_push($major, "Earth and Atmospheric Science");
    array_push($major, "Physics");
    array_push($major, "Psychology");
?>